// Code generated by goyacc - DO NOT EDIT.

package sql

import __yyfmt__ "fmt"

import (
	"strconv"
)

type yySymType struct {
	yys            int
	str            string
	strList        []string
	boolean        bool
	fieldType      FieldType
	compareOperate CompareOperate

	stmt     Statement
	stmtList []Statement

	createStmt        *CreateStmt
	createTable       *CreateTable
	createField       *CreateField
	createIndex       *CreateIndex
	createTableOption *CreateTableOption

	insertStmt  *InsertStmt
	insertValue [][]string

	updateStmt  *UpdateStmt
	updateValue map[string]string

	deleteStmt *DeleteStmt

	selectStmt      *SelectStmt
	selectFieldList []*SelectField
	selectWhereList []SelectWhere
	selectOrderList []*SelectOrder
	selectLimit     *SelectLimit
}

type yyXError struct {
	state, xsym int
}

const (
	yyDefault = 57376
	yyEofCode = 57344
	AND       = 57365
	ASC       = 57368
	BY        = 57367
	COMP_GE   = 57374
	COMP_LE   = 57373
	COMP_NE   = 57372
	CREATE    = 57346
	DEFAULT   = 57352
	DELETE    = 57360
	DESC      = 57369
	FROM      = 57362
	INDEX     = 57351
	INSERT    = 57354
	INTO      = 57355
	KEY       = 57348
	LIMIT     = 57370
	NOT       = 57349
	NULL      = 57350
	OFFSET    = 57371
	OR        = 57364
	ORDER     = 57366
	PRIMARY   = 57353
	SELECT    = 57361
	SET       = 57359
	TABLE     = 57347
	UPDATE    = 57358
	VALUE     = 57356
	VALUES    = 57357
	VARIABLE  = 57375
	WHERE     = 57363
	yyErrCode = 57345

	yyMaxDepth = 200
	yyTabOfs   = -71
)

var (
	yyPrec = map[int]int{
		OR:  0,
		AND: 1,
		'+': 2,
		'-': 2,
		'*': 3,
		'/': 3,
	}

	yyXLAT = map[int]int{
		44:    0,  // ',' (44x)
		57375: 1,  // VARIABLE (42x)
		59:    2,  // ';' (38x)
		41:    3,  // ')' (35x)
		57388: 4,  // Expr (32x)
		57370: 5,  // LIMIT (20x)
		57344: 6,  // $end (15x)
		57346: 7,  // CREATE (15x)
		57360: 8,  // DELETE (15x)
		57354: 9,  // INSERT (15x)
		57361: 10, // SELECT (15x)
		57358: 11, // UPDATE (15x)
		40:    12, // '(' (10x)
		57365: 13, // AND (9x)
		57364: 14, // OR (9x)
		57366: 15, // ORDER (9x)
		61:    16, // '=' (6x)
		57352: 17, // DEFAULT (6x)
		57363: 18, // WHERE (6x)
		57362: 19, // FROM (5x)
		57350: 20, // NULL (5x)
		57406: 21, // VaribleList (5x)
		60:    22, // '<' (4x)
		62:    23, // '>' (4x)
		57374: 24, // COMP_GE (4x)
		57373: 25, // COMP_LE (4x)
		57372: 26, // COMP_NE (4x)
		57368: 27, // ASC (3x)
		57379: 28, // CompareOperate (3x)
		57369: 29, // DESC (3x)
		57349: 30, // NOT (3x)
		57400: 31, // SelectWhere (3x)
		57401: 32, // SelectWhereList (3x)
		57378: 33, // Ascend (2x)
		57380: 34, // CreateField (2x)
		57381: 35, // CreateIndex (2x)
		57382: 36, // CreatePrimary (2x)
		57383: 37, // CreateStmt (2x)
		57387: 38, // DeleteStmt (2x)
		57351: 39, // INDEX (2x)
		57392: 40, // InsertStmt (2x)
		57394: 41, // InsertValueList (2x)
		57353: 42, // PRIMARY (2x)
		57396: 43, // SelectLimit (2x)
		57399: 44, // SelectStmt (2x)
		57359: 45, // SET (2x)
		57402: 46, // Stmt (2x)
		57404: 47, // UpdateStmt (2x)
		57356: 48, // VALUE (2x)
		57357: 49, // VALUES (2x)
		57377: 50, // AllowNull (1x)
		57367: 51, // BY (1x)
		57384: 52, // CreateTable (1x)
		57385: 53, // CreateTableOption (1x)
		57386: 54, // DefaultValue (1x)
		57389: 55, // FieldType (1x)
		57390: 56, // InsertField (1x)
		57391: 57, // InsertFieldList (1x)
		57393: 58, // InsertValue (1x)
		57355: 59, // INTO (1x)
		57348: 60, // KEY (1x)
		57371: 61, // OFFSET (1x)
		57395: 62, // SelectFieldList (1x)
		57397: 63, // SelectOrder (1x)
		57398: 64, // SelectOrderList (1x)
		57407: 65, // start (1x)
		57403: 66, // StmtList (1x)
		57347: 67, // TABLE (1x)
		57405: 68, // UpdateValue (1x)
		57376: 69, // $default (0x)
		42:    70, // '*' (0x)
		43:    71, // '+' (0x)
		45:    72, // '-' (0x)
		47:    73, // '/' (0x)
		57345: 74, // error (0x)
	}

	yySymNames = []string{
		"','",
		"VARIABLE",
		"';'",
		"')'",
		"Expr",
		"LIMIT",
		"$end",
		"CREATE",
		"DELETE",
		"INSERT",
		"SELECT",
		"UPDATE",
		"'('",
		"AND",
		"OR",
		"ORDER",
		"'='",
		"DEFAULT",
		"WHERE",
		"FROM",
		"NULL",
		"VaribleList",
		"'<'",
		"'>'",
		"COMP_GE",
		"COMP_LE",
		"COMP_NE",
		"ASC",
		"CompareOperate",
		"DESC",
		"NOT",
		"SelectWhere",
		"SelectWhereList",
		"Ascend",
		"CreateField",
		"CreateIndex",
		"CreatePrimary",
		"CreateStmt",
		"DeleteStmt",
		"INDEX",
		"InsertStmt",
		"InsertValueList",
		"PRIMARY",
		"SelectLimit",
		"SelectStmt",
		"SET",
		"Stmt",
		"UpdateStmt",
		"VALUE",
		"VALUES",
		"AllowNull",
		"BY",
		"CreateTable",
		"CreateTableOption",
		"DefaultValue",
		"FieldType",
		"InsertField",
		"InsertFieldList",
		"InsertValue",
		"INTO",
		"KEY",
		"OFFSET",
		"SelectFieldList",
		"SelectOrder",
		"SelectOrderList",
		"start",
		"StmtList",
		"TABLE",
		"UpdateValue",
		"$default",
		"'*'",
		"'+'",
		"'-'",
		"'/'",
		"error",
	}

	yyTokenLiteralStrings = map[int]string{
		57370: "LIMIT",
		57346: "CREATE",
		57360: "DELETE",
		57354: "INSERT",
		57361: "SELECT",
		57358: "UPDATE",
		57365: "AND",
		57364: "OR",
		57366: "ORDER",
		57352: "DEFAULT",
		57363: "WHERE",
		57362: "FROM",
		57350: "NULL",
		57374: ">=",
		57373: "<=",
		57372: "!=",
		57368: "ASC",
		57369: "DESC",
		57349: "NOT",
		57351: "INDEX",
		57353: "PRIMARY",
		57359: "SET",
		57356: "VALUE",
		57357: "VALUES",
		57367: "BY",
		57355: "INTO",
		57348: "KEY",
		57371: "OFFSET",
		57347: "TABLE",
	}

	yyReductions = map[int]struct{ xsym, components int }{
		0:  {0, 1},
		1:  {65, 1},
		2:  {4, 1},
		3:  {21, 1},
		4:  {21, 3},
		5:  {46, 1},
		6:  {46, 1},
		7:  {46, 1},
		8:  {46, 1},
		9:  {46, 1},
		10: {66, 1},
		11: {66, 2},
		12: {50, 0},
		13: {50, 1},
		14: {50, 2},
		15: {54, 0},
		16: {54, 1},
		17: {54, 2},
		18: {54, 2},
		19: {55, 1},
		20: {37, 8},
		21: {52, 1},
		22: {52, 1},
		23: {52, 1},
		24: {52, 3},
		25: {52, 3},
		26: {52, 3},
		27: {34, 4},
		28: {35, 5},
		29: {36, 5},
		30: {53, 0},
		31: {40, 6},
		32: {56, 3},
		33: {57, 0},
		34: {57, 1},
		35: {58, 2},
		36: {58, 2},
		37: {41, 3},
		38: {41, 5},
		39: {47, 6},
		40: {68, 3},
		41: {68, 5},
		42: {38, 5},
		43: {33, 0},
		44: {33, 1},
		45: {33, 1},
		46: {28, 1},
		47: {28, 1},
		48: {28, 1},
		49: {28, 1},
		50: {28, 1},
		51: {28, 1},
		52: {44, 4},
		53: {44, 8},
		54: {62, 1},
		55: {62, 3},
		56: {31, 0},
		57: {31, 2},
		58: {32, 3},
		59: {32, 5},
		60: {32, 5},
		61: {32, 5},
		62: {32, 5},
		63: {63, 0},
		64: {63, 3},
		65: {64, 2},
		66: {64, 4},
		67: {43, 0},
		68: {43, 2},
		69: {43, 4},
		70: {43, 4},
	}

	yyXErrors = map[yyXError]string{}

	yyParseTab = [143][]uint16{
		// 0
		{7: 80, 83, 81, 84, 82, 37: 74, 78, 40: 76, 44: 75, 46: 79, 77, 65: 72, 73},
		{6: 71},
		{6: 70, 80, 83, 81, 84, 82, 37: 74, 78, 40: 76, 44: 75, 46: 213, 77},
		{6: 66, 66, 66, 66, 66, 66},
		{6: 65, 65, 65, 65, 65, 65},
		// 5
		{6: 64, 64, 64, 64, 64, 64},
		{6: 63, 63, 63, 63, 63, 63},
		{6: 62, 62, 62, 62, 62, 62},
		{6: 61, 61, 61, 61, 61, 61},
		{67: 178},
		// 10
		{59: 155},
		{1: 85, 4: 143},
		{19: 139},
		{1: 85, 4: 87, 62: 86},
		{69, 69, 69, 69, 5: 69, 12: 69, 69, 69, 69, 69, 69, 69, 69, 69, 22: 69, 69, 69, 69, 69, 69, 29: 69, 69, 45: 69},
		// 15
		{90, 2: 4, 5: 91, 19: 89, 43: 88},
		{17, 2: 17, 5: 17, 19: 17},
		{2: 138},
		{1: 85, 4: 98},
		{1: 85, 4: 97},
		// 20
		{1: 92},
		{93, 2: 3, 61: 94},
		{1: 96},
		{1: 95},
		{2: 1},
		// 25
		{2: 2},
		{16, 2: 16, 5: 16, 19: 16},
		{2: 15, 5: 15, 15: 15, 18: 100, 31: 99},
		{2: 8, 5: 8, 15: 126, 63: 125},
		{1: 85, 4: 102, 32: 101},
		// 30
		{2: 14, 5: 14, 13: 112, 111, 14},
		{16: 103, 22: 104, 105, 107, 106, 108, 28: 109},
		{1: 25},
		{1: 24},
		{1: 23},
		// 35
		{1: 22},
		{1: 21},
		{1: 20},
		{1: 85, 4: 110},
		{2: 13, 13, 5: 13, 13: 13, 13, 13},
		// 40
		{1: 85, 4: 119, 12: 120},
		{1: 85, 4: 113, 12: 114},
		{16: 103, 22: 104, 105, 107, 106, 108, 28: 117},
		{1: 85, 4: 102, 32: 115},
		{3: 116, 13: 112, 111},
		// 45
		{2: 9, 9, 5: 9, 13: 9, 9, 9},
		{1: 85, 4: 118},
		{2: 11, 11, 5: 11, 13: 11, 11, 11},
		{16: 103, 22: 104, 105, 107, 106, 108, 28: 123},
		{1: 85, 4: 102, 32: 121},
		// 50
		{3: 122, 13: 112, 111},
		{2: 10, 10, 5: 10, 13: 10, 10, 10},
		{1: 85, 4: 124},
		{2: 12, 12, 5: 12, 13: 12, 12, 12},
		{2: 4, 5: 91, 43: 136},
		// 55
		{51: 127},
		{1: 85, 4: 129, 64: 128},
		{133, 2: 7, 5: 7},
		{28, 2: 28, 5: 28, 27: 130, 29: 131, 33: 132},
		{27, 2: 27, 5: 27},
		// 60
		{26, 2: 26, 5: 26},
		{6, 2: 6, 5: 6},
		{1: 85, 4: 134},
		{28, 2: 28, 5: 28, 27: 130, 29: 131, 33: 135},
		{5, 2: 5, 5: 5},
		// 65
		{2: 137},
		{6: 18, 18, 18, 18, 18, 18},
		{6: 19, 19, 19, 19, 19, 19},
		{1: 85, 4: 140},
		{2: 15, 18: 100, 31: 141},
		// 70
		{2: 142},
		{6: 29, 29, 29, 29, 29, 29},
		{45: 144},
		{1: 85, 4: 146, 68: 145},
		{150, 2: 15, 18: 100, 31: 149},
		// 75
		{16: 147},
		{1: 85, 4: 148},
		{31, 2: 31, 18: 31},
		{2: 154},
		{1: 85, 4: 151},
		// 80
		{16: 152},
		{1: 85, 4: 153},
		{30, 2: 30, 18: 30},
		{6: 32, 32, 32, 32, 32, 32},
		{1: 85, 4: 156},
		// 85
		{12: 158, 56: 157},
		{48: 166, 167, 58: 165},
		{1: 85, 3: 38, 159, 21: 160, 57: 161},
		{68, 3: 68},
		{163, 3: 37},
		// 90
		{3: 162},
		{48: 39, 39},
		{1: 85, 4: 164},
		{67, 3: 67},
		{2: 177},
		// 95
		{12: 169, 41: 176},
		{12: 169, 41: 168},
		{172, 2: 35},
		{1: 85, 4: 159, 21: 170},
		{163, 3: 171},
		// 100
		{34, 2: 34},
		{12: 173},
		{1: 85, 4: 159, 21: 174},
		{163, 3: 175},
		{33, 2: 33},
		// 105
		{172, 2: 36},
		{6: 40, 40, 40, 40, 40, 40},
		{1: 85, 4: 179},
		{12: 180},
		{1: 85, 4: 185, 34: 182, 183, 184, 39: 186, 42: 187, 52: 181},
		// 110
		{207, 3: 206},
		{50, 3: 50},
		{49, 3: 49},
		{48, 3: 48},
		{1: 85, 4: 196, 55: 197},
		// 115
		{1: 85, 4: 192},
		{60: 188},
		{12: 189},
		{1: 85, 4: 159, 21: 190},
		{163, 3: 191},
		// 120
		{42, 3: 42},
		{12: 193},
		{1: 85, 4: 159, 21: 194},
		{163, 3: 195},
		{43, 3: 43},
		// 125
		{52, 3: 52, 17: 52, 20: 52, 30: 52},
		{59, 3: 59, 17: 59, 20: 198, 30: 199, 50: 200},
		{58, 3: 58, 17: 58},
		{20: 205},
		{56, 3: 56, 17: 201, 54: 202},
		// 130
		{55, 85, 3: 55, 204, 20: 203},
		{44, 3: 44},
		{54, 3: 54},
		{53, 3: 53},
		{57, 3: 57, 17: 57},
		// 135
		{2: 41, 53: 211},
		{1: 85, 4: 185, 34: 208, 209, 210, 39: 186, 42: 187},
		{47, 3: 47},
		{46, 3: 46},
		{45, 3: 45},
		// 140
		{2: 212},
		{6: 51, 51, 51, 51, 51, 51},
		{6: 60, 60, 60, 60, 60, 60},
	}
)

var yyDebug = 0

type yyLexer interface {
	Lex(lval *yySymType) int
	Error(s string)
}

type yyLexerEx interface {
	yyLexer
	Reduced(rule, state int, lval *yySymType) bool
}

func yySymName(c int) (s string) {
	x, ok := yyXLAT[c]
	if ok {
		return yySymNames[x]
	}

	if c < 0x7f {
		return __yyfmt__.Sprintf("%q", c)
	}

	return __yyfmt__.Sprintf("%d", c)
}

func yylex1(yylex yyLexer, lval *yySymType) (n int) {
	n = yylex.Lex(lval)
	if n <= 0 {
		n = yyEofCode
	}
	if yyDebug >= 3 {
		__yyfmt__.Printf("\nlex %s(%#x %d), lval: %+v\n", yySymName(n), n, n, lval)
	}
	return n
}

func yyParse(yylex yyLexer) int {
	const yyError = 74

	yyEx, _ := yylex.(yyLexerEx)
	var yyn int
	var yylval yySymType
	var yyVAL yySymType
	yyS := make([]yySymType, 200)

	Nerrs := 0   /* number of errors */
	Errflag := 0 /* error recovery flag */
	yyerrok := func() {
		if yyDebug >= 2 {
			__yyfmt__.Printf("yyerrok()\n")
		}
		Errflag = 0
	}
	_ = yyerrok
	yystate := 0
	yychar := -1
	var yyxchar int
	var yyshift int
	yyp := -1
	goto yystack

ret0:
	return 0

ret1:
	return 1

yystack:
	/* put a state and value onto the stack */
	yyp++
	if yyp >= len(yyS) {
		nyys := make([]yySymType, len(yyS)*2)
		copy(nyys, yyS)
		yyS = nyys
	}
	yyS[yyp] = yyVAL
	yyS[yyp].yys = yystate

yynewstate:
	if yychar < 0 {
		yylval.yys = yystate
		yychar = yylex1(yylex, &yylval)
		var ok bool
		if yyxchar, ok = yyXLAT[yychar]; !ok {
			yyxchar = len(yySymNames) // > tab width
		}
	}
	if yyDebug >= 4 {
		var a []int
		for _, v := range yyS[:yyp+1] {
			a = append(a, v.yys)
		}
		__yyfmt__.Printf("state stack %v\n", a)
	}
	row := yyParseTab[yystate]
	yyn = 0
	if yyxchar < len(row) {
		if yyn = int(row[yyxchar]); yyn != 0 {
			yyn += yyTabOfs
		}
	}
	switch {
	case yyn > 0: // shift
		yychar = -1
		yyVAL = yylval
		yystate = yyn
		yyshift = yyn
		if yyDebug >= 2 {
			__yyfmt__.Printf("shift, and goto state %d\n", yystate)
		}
		if Errflag > 0 {
			Errflag--
		}
		goto yystack
	case yyn < 0: // reduce
	case yystate == 1: // accept
		if yyDebug >= 2 {
			__yyfmt__.Println("accept")
		}
		goto ret0
	}

	if yyn == 0 {
		/* error ... attempt to resume parsing */
		switch Errflag {
		case 0: /* brand new error */
			if yyDebug >= 1 {
				__yyfmt__.Printf("no action for %s in state %d\n", yySymName(yychar), yystate)
			}
			msg, ok := yyXErrors[yyXError{yystate, yyxchar}]
			if !ok {
				msg, ok = yyXErrors[yyXError{yystate, -1}]
			}
			if !ok && yyshift != 0 {
				msg, ok = yyXErrors[yyXError{yyshift, yyxchar}]
			}
			if !ok {
				msg, ok = yyXErrors[yyXError{yyshift, -1}]
			}
			if yychar > 0 {
				ls := yyTokenLiteralStrings[yychar]
				if ls == "" {
					ls = yySymName(yychar)
				}
				if ls != "" {
					switch {
					case msg == "":
						msg = __yyfmt__.Sprintf("unexpected %s", ls)
					default:
						msg = __yyfmt__.Sprintf("unexpected %s, %s", ls, msg)
					}
				}
			}
			if msg == "" {
				msg = "syntax error"
			}
			yylex.Error(msg)
			Nerrs++
			fallthrough

		case 1, 2: /* incompletely recovered error ... try again */
			Errflag = 3

			/* find a state where "error" is a legal shift action */
			for yyp >= 0 {
				row := yyParseTab[yyS[yyp].yys]
				if yyError < len(row) {
					yyn = int(row[yyError]) + yyTabOfs
					if yyn > 0 { // hit
						if yyDebug >= 2 {
							__yyfmt__.Printf("error recovery found error shift in state %d\n", yyS[yyp].yys)
						}
						yystate = yyn /* simulate a shift of "error" */
						goto yystack
					}
				}

				/* the current p has no shift on "error", pop stack */
				if yyDebug >= 2 {
					__yyfmt__.Printf("error recovery pops state %d\n", yyS[yyp].yys)
				}
				yyp--
			}
			/* there is no state on the stack with an error shift ... abort */
			if yyDebug >= 2 {
				__yyfmt__.Printf("error recovery failed\n")
			}
			goto ret1

		case 3: /* no shift yet; clobber input char */
			if yyDebug >= 2 {
				__yyfmt__.Printf("error recovery discards %s\n", yySymName(yychar))
			}
			if yychar == yyEofCode {
				goto ret1
			}

			yychar = -1
			goto yynewstate /* try again in the same state */
		}
	}

	r := -yyn
	x0 := yyReductions[r]
	x, n := x0.xsym, x0.components
	yypt := yyp
	_ = yypt // guard against "declared and not used"

	yyp -= n
	if yyp+1 >= len(yyS) {
		nyys := make([]yySymType, len(yyS)*2)
		copy(nyys, yyS)
		yyS = nyys
	}
	yyVAL = yyS[yyp+1]

	/* consult goto table to find next state */
	exState := yystate
	yystate = int(yyParseTab[yyS[yyp].yys][x]) + yyTabOfs
	/* reduction by production r */
	if yyDebug >= 2 {
		__yyfmt__.Printf("reduce using rule %v (%s), and goto state %d\n", r, yySymNames[x], yystate)
	}

	switch r {
	case 2:
		{
			str, err := TrimQuote(yyS[yypt-0].str)
			if err != nil {
				yylex.Error(err.Error())
				goto ret1
			}
			yyVAL.str = str
		}
	case 3:
		{
			yyVAL.strList = []string{yyS[yypt-0].str}
		}
	case 4:
		{
			yyVAL.strList = append(yyS[yypt-2].strList, yyS[yypt-0].str)
		}
	case 5:
		{
			yyVAL.stmt = Statement(yyS[yypt-0].createStmt)
		}
	case 6:
		{
			yyVAL.stmt = Statement(yyS[yypt-0].selectStmt)
		}
	case 7:
		{
			yyVAL.stmt = Statement(yyS[yypt-0].insertStmt)
		}
	case 8:
		{
			yyVAL.stmt = Statement(yyS[yypt-0].updateStmt)
		}
	case 9:
		{
			yyVAL.stmt = Statement(yyS[yypt-0].deleteStmt)
		}
	case 10:
		{
			yyVAL.stmtList = append(yyVAL.stmtList, yyS[yypt-0].stmt)
		}
	case 11:
		{
			yyVAL.stmtList = append(yyVAL.stmtList, yyS[yypt-0].stmt)
		}
	case 12:
		{
			yyVAL.boolean = true
		}
	case 13:
		{
			yyVAL.boolean = true
		}
	case 14:
		{
			yyVAL.boolean = false
		}
	case 15:
		{
			yyVAL.str = ""
		}
	case 16:
		{
			yyVAL.str = ""
		}
	case 17:
		{
			yyVAL.str = ""
		}
	case 18:
		{
			yyVAL.str = yyS[yypt-0].str
		}
	case 19:
		{
			t, ok := typeMapping[yyS[yypt-0].str]
			if ok {
				yyVAL.fieldType = t
			} else {
				__yyfmt__.Printf("不支持的数据类型 %s", yyS[yypt-0].str)
				goto ret1
			}
		}
	case 20:
		{
			yyVAL.createStmt = &CreateStmt{
				Name:   yyS[yypt-5].str,
				Table:  yyS[yypt-3].createTable,
				Option: yyS[yypt-1].createTableOption,
			}
		}
	case 21:
		{
			yyVAL.createTable = &CreateTable{
				Field: []*CreateField{yyS[yypt-0].createField},
				Index: []*CreateIndex{},
			}
		}
	case 22:
		{
			yyVAL.createTable = &CreateTable{
				Field: []*CreateField{},
				Index: []*CreateIndex{yyS[yypt-0].createIndex},
			}
		}
	case 23:
		{
			yyVAL.createTable = &CreateTable{
				Pk:    yyS[yypt-0].createIndex,
				Field: []*CreateField{},
				Index: []*CreateIndex{},
			}
		}
	case 24:
		{
			yyVAL.createTable.Field = append(yyVAL.createTable.Field, yyS[yypt-0].createField)
		}
	case 25:
		{
			yyVAL.createTable.Index = append(yyVAL.createTable.Index, yyS[yypt-0].createIndex)
		}
	case 26:
		{
			if yyVAL.createTable.Pk == nil {
				yyVAL.createTable.Pk = yyS[yypt-0].createIndex
			} else {
				__yyfmt__.Printf("重复定义主键 %v %v ", yyVAL.createTable.Pk, yyS[yypt-0].createIndex)
				goto ret1
			}
		}
	case 27:
		{
			yyVAL.createField = &CreateField{
				Name:         yyS[yypt-3].str,
				Type:         yyS[yypt-2].fieldType,
				AllowNull:    yyS[yypt-1].boolean,
				DefaultValue: yyS[yypt-0].str,
			}
		}
	case 28:
		{
			yyVAL.createIndex = &CreateIndex{
				Name:  yyS[yypt-3].str,
				Field: yyS[yypt-1].strList,
			}
		}
	case 29:
		{
			yyVAL.createIndex = &CreateIndex{
				Pk:    true,
				Field: yyS[yypt-1].strList,
			}
		}
	case 30:
		{
			yyVAL.createTableOption = nil
		}
	case 31:
		{
			yyVAL.insertStmt = &InsertStmt{
				Table:  yyS[yypt-3].str,
				Fields: yyS[yypt-2].strList,
				Values: yyS[yypt-1].insertValue,
			}
		}
	case 32:
		{
			yyVAL.strList = yyS[yypt-1].strList
		}
	case 33:
		{
			yyVAL.strList = nil
		}
	case 35:
		{
			yyVAL.insertValue = yyS[yypt-0].insertValue
		}
	case 36:
		{
			yyVAL.insertValue = yyS[yypt-0].insertValue
		}
	case 37:
		{
			yyVAL.insertValue = [][]string{yyS[yypt-1].strList}
		}
	case 38:
		{
			yyVAL.insertValue = append(yyS[yypt-4].insertValue, yyS[yypt-1].strList)
		}
	case 39:
		{
			yyVAL.updateStmt = &UpdateStmt{
				Table: yyS[yypt-4].str,
				Value: yyS[yypt-2].updateValue,
				Where: yyS[yypt-1].selectWhereList,
			}
		}
	case 40:
		{
			yyVAL.updateValue = map[string]string{
				yyS[yypt-2].str: yyS[yypt-0].str,
			}
		}
	case 41:
		{
			yyVAL.updateValue[yyS[yypt-2].str] = yyS[yypt-0].str
		}
	case 42:
		{
			yyVAL.deleteStmt = &DeleteStmt{
				Table: yyS[yypt-2].str,
				Where: yyS[yypt-1].selectWhereList,
			}
		}
	case 43:
		{
			yyVAL.boolean = true
		}
	case 44:
		{
			yyVAL.boolean = true
		}
	case 45:
		{
			yyVAL.boolean = false
		}
	case 46:
		{
			yyVAL.compareOperate = EQ
		}
	case 47:
		{
			yyVAL.compareOperate = LT
		}
	case 48:
		{
			yyVAL.compareOperate = GT
		}
	case 49:
		{
			yyVAL.compareOperate = LE
		}
	case 50:
		{
			yyVAL.compareOperate = GE
		}
	case 51:
		{
			yyVAL.compareOperate = NE
		}
	case 52:
		{
			yyVAL.selectStmt = &SelectStmt{
				Field: yyS[yypt-2].selectFieldList,
				Limit: yyS[yypt-1].selectLimit,
			}
		}
	case 53:
		{
			yyVAL.selectStmt = &SelectStmt{
				Table: yyS[yypt-4].str,
				Field: yyS[yypt-6].selectFieldList,
				Where: yyS[yypt-3].selectWhereList,
				Order: yyS[yypt-2].selectOrderList,
				Limit: yyS[yypt-1].selectLimit,
			}
		}
	case 54:
		{
			yyVAL.selectFieldList = []*SelectField{
				&SelectField{
					Name: yyS[yypt-0].str,
				},
			}
		}
	case 55:
		{
			yyVAL.selectFieldList = append(yyS[yypt-2].selectFieldList, &SelectField{
				Name: yyS[yypt-0].str,
			})
		}
	case 56:
		{
			yyVAL.selectWhereList = nil
		}
	case 57:
		{
			yyVAL.selectWhereList = yyS[yypt-0].selectWhereList
		}
	case 58:
		{
			yyVAL.selectWhereList = []SelectWhere{
				&SelectWhereField{
					Field:   yyS[yypt-2].str,
					Value:   yyS[yypt-0].str,
					Operate: yyS[yypt-1].compareOperate,
				},
			}
		}
	case 59:
		{
			yyS[yypt-1].compareOperate.Negate()
			field := &SelectWhereField{
				Field:   yyS[yypt-2].str,
				Value:   yyS[yypt-0].str,
				Operate: yyS[yypt-1].compareOperate,
			}
			if len(yyVAL.selectWhereList) == 1 {
				yyVAL.selectWhereList[0].Negate()
				yyVAL.selectWhereList = append(yyVAL.selectWhereList, field)
				yyVAL.selectWhereList = []SelectWhere{
					&SelectWhereExpr{
						Negation: true,
						Cnf:      yyVAL.selectWhereList,
					},
				}
			} else {
				yyVAL.selectWhereList = []SelectWhere{
					&SelectWhereExpr{
						Negation: true,
						Cnf: []SelectWhere{
							&SelectWhereExpr{
								Negation: true,
								Cnf:      yyVAL.selectWhereList,
							},
							field,
						},
					},
				}
			}
		}
	case 60:
		{
			yyVAL.selectWhereList = append(yyVAL.selectWhereList, &SelectWhereField{
				Field:   yyS[yypt-2].str,
				Value:   yyS[yypt-0].str,
				Operate: yyS[yypt-1].compareOperate,
			})
		}
	case 61:
		{
			expr := &SelectWhereExpr{
				Negation: true,
				Cnf:      yyS[yypt-1].selectWhereList,
			}
			if len(yyVAL.selectWhereList) == 1 {
				yyVAL.selectWhereList[0].Negate()
				yyVAL.selectWhereList = append(yyVAL.selectWhereList, expr)
				yyVAL.selectWhereList = []SelectWhere{
					&SelectWhereExpr{
						Negation: true,
						Cnf:      yyVAL.selectWhereList,
					},
				}
			} else {
				yyVAL.selectWhereList = []SelectWhere{
					&SelectWhereExpr{
						Negation: true,
						Cnf: []SelectWhere{
							&SelectWhereExpr{
								Negation: true,
								Cnf:      yyVAL.selectWhereList,
							},
							expr,
						},
					},
				}
			}
		}
	case 62:
		{
			yyVAL.selectWhereList = append(yyVAL.selectWhereList, yyS[yypt-1].selectWhereList...)
		}
	case 63:
		{
			yyVAL.selectOrderList = nil
		}
	case 64:
		{
			yyVAL.selectOrderList = yyS[yypt-0].selectOrderList
		}
	case 65:
		{
			yyVAL.selectOrderList = []*SelectOrder{
				&SelectOrder{
					Asc:   yyS[yypt-0].boolean,
					Field: yyS[yypt-1].str,
				},
			}
		}
	case 66:
		{
			yyVAL.selectOrderList = append(yyS[yypt-3].selectOrderList, &SelectOrder{
				Asc:   yyS[yypt-0].boolean,
				Field: yyS[yypt-1].str,
			})
		}
	case 67:
		{
			yyVAL.selectLimit = nil
		}
	case 68:
		{
			limit, err := strconv.Atoi(yyS[yypt-0].str)
			if err != nil {
				yylex.Error(err.Error())
				goto ret1
			}
			yyVAL.selectLimit = &SelectLimit{
				Limit: limit,
			}
		}
	case 69:
		{
			limit, err := strconv.Atoi(yyS[yypt-2].str)
			if err != nil {
				yylex.Error(err.Error())
				goto ret1
			}
			offset, err := strconv.Atoi(yyS[yypt-0].str)
			if err != nil {
				yylex.Error(err.Error())
				goto ret1
			}
			yyVAL.selectLimit = &SelectLimit{
				Limit:  limit,
				Offset: offset,
			}
		}
	case 70:
		{
			limit, err := strconv.Atoi(yyS[yypt-2].str)
			if err != nil {
				yylex.Error(err.Error())
				goto ret1
			}
			offset, err := strconv.Atoi(yyS[yypt-0].str)
			if err != nil {
				yylex.Error(err.Error())
				goto ret1
			}
			yyVAL.selectLimit = &SelectLimit{
				Limit:  limit,
				Offset: offset,
			}
		}

	}

	if yyEx != nil && yyEx.Reduced(r, exState, &yyVAL) {
		return -1
	}
	goto yystack /* stack new state and value */
}
